/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentrecordapp;

import Students_Result.Student_Result;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author MUC
 */
public class BiologyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BiologyJFrame
     */
    public BiologyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSName = new javax.swing.JTextField();
        jTextFieldTest3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTest2 = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jComboBoxTerm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jTextFieldAss1 = new javax.swing.JTextField();
        jButtonUpdate1 = new javax.swing.JButton();
        jTextFieldFName = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAss4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAss2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAss3 = new javax.swing.JTextField();
        jTextFieldTest1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setText("Test 1");

        jLabel5.setText("Total");

        jLabel8.setText("ID ");

        jLabel4.setText("Test 3");

        jLabel10.setText("Assignment 3");

        jLabel13.setText("Term");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jComboBoxTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBoxTerm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTermMouseClicked(evt);
            }
        });
        jComboBoxTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTermActionPerformed(evt);
            }
        });

        jLabel9.setText("Assignment 4");

        jLabel6.setText("Surname");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonUpdate1.setText("Update");
        jButtonUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1ActionPerformed(evt);
            }
        });

        jTextFieldFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Firstname");

        jLabel11.setText("Assignment 2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Enter tests and assignments marks for Biology");

        jLabel2.setText("Test 2");

        jLabel12.setText("Assignment 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldTotal)
                            .addComponent(jTextFieldFName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonAdd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAss3)
                                .addComponent(jTextFieldAss4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAss2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAss1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd)
                            .addComponent(jButtonExit)
                            .addComponent(jButtonUpdate1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAss1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldAss2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldAss3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldAss4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // Adds all the marks to give total
        double[] R = new double[14];
        R[0] = Double.parseDouble(jTextFieldTest1.getText());
        R[1] = Double.parseDouble(jTextFieldTest2.getText());
        R[2] = Double.parseDouble(jTextFieldTest3.getText());
        R[3] = Double.parseDouble(jTextFieldAss1.getText());
        R[4] = Double.parseDouble(jTextFieldAss2.getText());
        R[5] = Double.parseDouble(jTextFieldAss3.getText());
        R[6] = Double.parseDouble(jTextFieldAss4.getText());

        R[7]= R[0]+R[1]+R[2]+R[3]+R[4]+R[5]+R[6];
        String TotalEngScore = String.format("%.0f", R[7]);
        jTextFieldTotal.setText(TotalEngScore);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxTermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTermMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTermMouseClicked

    private void jComboBoxTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTermActionPerformed
        // Accepts jcombobox options
        jComboBoxTerm.getActionListeners();
        // jComboBoxTerm.addActionListener((ActionListener) this);

        // int selection=jComboBoxTerm.getSelectedIndex();
    }//GEN-LAST:event_jComboBoxTermActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // exits out of the window
        try{
            dispose();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1ActionPerformed
        // Updates the total of english marks to database
        String qry=null;
        PreparedStatement ps=null;

        Connection conn=MySqlConnection();

        if(jTextFieldId!=null && jTextFieldFName!=null && jTextFieldSName!=null
            || jTextFieldTest1!=null || jTextFieldTest2!=null || jTextFieldTest3!=null
            || jTextFieldTotal!=null || jTextFieldAss1!= null || jTextFieldAss2!=null
            || jTextFieldAss3!=null || jTextFieldAss4!=null){

            String term=jComboBoxTerm.getSelectedItem().toString();
            switch(term)
            {
                case "1": conn=MySqlConnection();
                try{
                    qry=null;
                    ps=null;
                    qry="update term1 set FirstName=?, LastName=? , AT1=?, AT2=?, "
                    + "AT3=?, AS1=?,AS2=?, AS3=?, AS4=?, Arts=? "
                    +" where SID=?";
                    ps=conn.prepareStatement(qry);
                    ps.setString(1, jTextFieldFName.getText());
                    ps.setString(2, jTextFieldSName.getText());
                    ps.setInt(3, Integer.parseInt(jTextFieldTest1.getText()));
                    ps.setInt(4, Integer.parseInt(jTextFieldTest2.getText()));

                    ps.setInt(5, Integer.parseInt(jTextFieldTest3.getText()));
                    ps.setInt(6, Integer.parseInt(jTextFieldAss1.getText()));
                    ps.setInt(7, Integer.parseInt(jTextFieldAss2.getText()));
                    ps.setInt(8, Integer.parseInt(jTextFieldAss3.getText()));
                    ps.setInt(9, Integer.parseInt(jTextFieldAss4.getText()));
                    ps.setInt(10, Integer.parseInt(jTextFieldTotal.getText()));
                    ps.setInt(11, Integer.parseInt(jTextFieldId.getText()));

                    int res=ps.executeUpdate();

                    Statement st=null;
                    Statement st2=null;
                    ResultSet rs=null;
                    ResultSet rs2=null;
                    st=conn.createStatement();

                    if(res>=1){
                        JOptionPane.showMessageDialog(null, res+" Number of students"
                            +" updated successfully...");
                    }else
                    JOptionPane.showMessageDialog(null, " Student updation fail: term1...");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

                String qry2=null;
                PreparedStatement ps2=null;

                qry2 = "UPDATE term1"
                + " SET Total_Score = English+Science+Social_Science"
                + "+Maths+Making_A_Living+Health_PE+Arts"
                + " WHERE SID = ?";

                int res2;
                try{
                    ps2 = conn.prepareStatement(qry2);
                    ps2.setInt(1, Integer.parseInt(jTextFieldId.getText()));
                    res2=ps2.executeUpdate();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null , e);

                }

                break;
                case "2": conn=MySqlConnection();
                try{
                    qry=null;
                    ps=null;
                    qry="update term2 set FirstName=?, LastName=? , AT1=?, AT2=?, "
                    + "AT3=?, AS1=?,AS2=?, AS3=?, AS4=?, Arts=? where StudentID=?";
                    ps=conn.prepareStatement(qry);
                    ps.setString(1, jTextFieldFName.getText());
                    ps.setString(2, jTextFieldSName.getText());
                    ps.setInt(3, Integer.parseInt(jTextFieldTest1.getText()));
                    ps.setInt(4, Integer.parseInt(jTextFieldTest2.getText()));

                    ps.setInt(5, Integer.parseInt(jTextFieldTest3.getText()));
                    ps.setInt(6, Integer.parseInt(jTextFieldAss1.getText()));
                    ps.setInt(7, Integer.parseInt(jTextFieldAss2.getText()));
                    ps.setInt(8, Integer.parseInt(jTextFieldAss3.getText()));
                    ps.setInt(9, Integer.parseInt(jTextFieldAss4.getText()));
                    ps.setInt(10, Integer.parseInt(jTextFieldTotal.getText()));
                    ps.setInt(11, Integer.parseInt(jTextFieldId.getText()));

                    int res=ps.executeUpdate();
                    if(res>=1){
                        JOptionPane.showMessageDialog(null, res+" Number of students"
                            +" updated successfully...");
                    }else
                    JOptionPane.showMessageDialog(null, " Student updation fail T2...");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

                qry2=null;
                ps2=null;

                qry2 = "UPDATE term2"
                + " SET Total_Score = English+Science+Social_Science"
                + "+Maths+Making_A_Living+Health_PE+Arts"
                + " WHERE StudentID = ?";

                try{
                    ps2 = conn.prepareStatement(qry2);
                    ps2.setInt(1, Integer.parseInt(jTextFieldId.getText()));
                    res2=ps2.executeUpdate();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null , e);

                }

                break;
                case "3": conn=MySqlConnection();
                try{
                    qry=null;
                    ps=null;
                    qry="update term3 set FirstName=?, LastName=? , AT1=?, AT2=?, "
                    + "AT3=?, AS1=?,AS2=?, AS3=?, AS4=?, Arts=? where StudentID=?";
                    ps=conn.prepareStatement(qry);
                    ps.setString(1, jTextFieldFName.getText());
                    ps.setString(2, jTextFieldSName.getText());
                    ps.setInt(3, Integer.parseInt(jTextFieldTest1.getText()));
                    ps.setInt(4, Integer.parseInt(jTextFieldTest2.getText()));

                    ps.setInt(5, Integer.parseInt(jTextFieldTest3.getText()));
                    ps.setInt(6, Integer.parseInt(jTextFieldAss1.getText()));
                    ps.setInt(7, Integer.parseInt(jTextFieldAss2.getText()));
                    ps.setInt(8, Integer.parseInt(jTextFieldAss3.getText()));
                    ps.setInt(9, Integer.parseInt(jTextFieldAss4.getText()));
                    ps.setInt(10, Integer.parseInt(jTextFieldTotal.getText()));
                    ps.setInt(11, Integer.parseInt(jTextFieldId.getText()));

                    int res=ps.executeUpdate();
                    if(res>=1){
                        JOptionPane.showMessageDialog(null, res+" Number of students"
                            +" updated successfully...");
                    }else
                    JOptionPane.showMessageDialog(null, " Student updation fail T3...");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

                qry2=null;
                ps2=null;

                qry2 = "UPDATE term3"
                + " SET Total_Score = English+Science+Social_Science"
                + "+Maths+Making_A_Living+Health_PE+Arts"
                + " WHERE StudentID = ?";

                try{
                    ps2 = conn.prepareStatement(qry2);
                    ps2.setInt(1, Integer.parseInt(jTextFieldId.getText()));
                    res2=ps2.executeUpdate();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null , e);

                }

                break;
                case "4": conn=MySqlConnection();
                try{
                    qry=null;
                    ps=null;
                    qry="update term4 set FirstName=?, LastName=? , AT1=?, AT2=?, "
                    + "AT3=?, AS1=?,AS2=?, AS3=?, AS4=?, Arts=? where StudentID=?";
                    ps=conn.prepareStatement(qry);
                    ps.setString(1, jTextFieldFName.getText());
                    ps.setString(2, jTextFieldSName.getText());
                    ps.setInt(3, Integer.parseInt(jTextFieldTest1.getText()));
                    ps.setInt(4, Integer.parseInt(jTextFieldTest2.getText()));

                    ps.setInt(5, Integer.parseInt(jTextFieldTest3.getText()));
                    ps.setInt(6, Integer.parseInt(jTextFieldAss1.getText()));
                    ps.setInt(7, Integer.parseInt(jTextFieldAss2.getText()));
                    ps.setInt(8, Integer.parseInt(jTextFieldAss3.getText()));
                    ps.setInt(9, Integer.parseInt(jTextFieldAss4.getText()));
                    ps.setInt(10, Integer.parseInt(jTextFieldTotal.getText()));
                    ps.setInt(11, Integer.parseInt(jTextFieldId.getText()));

                    int res=ps.executeUpdate();
                    if(res>=1){
                        JOptionPane.showMessageDialog(null, res+" Number of students"
                            +" updated successfully...");
                    }else
                    JOptionPane.showMessageDialog(null, " Student updation fail T4...");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }

                qry2=null;
                ps2=null;

                qry2 = "UPDATE term4"
                + " SET Total_Score = English+Science+Social_Science"
                + "+Maths+Making_A_Living+Health_PE+Arts"
                + " WHERE StudentID = ?";

                try{
                    ps2 = conn.prepareStatement(qry2);
                    ps2.setInt(1, Integer.parseInt(jTextFieldId.getText()));
                    res2=ps2.executeUpdate();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null , e);

                }

                break;
                default: break;

            }
        }
    }//GEN-LAST:event_jButtonUpdate1ActionPerformed

    private void jTextFieldFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiologyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiologyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiologyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiologyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiologyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonUpdate1;
    private javax.swing.JComboBox<String> jComboBoxTerm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAss1;
    private javax.swing.JTextField jTextFieldAss2;
    private javax.swing.JTextField jTextFieldAss3;
    private javax.swing.JTextField jTextFieldAss4;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldSName;
    private javax.swing.JTextField jTextFieldTest1;
    private javax.swing.JTextField jTextFieldTest2;
    private javax.swing.JTextField jTextFieldTest3;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

private Connection MySqlConnection() {
        Connection conn=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/studentrecord",
                    "root", "sTud397r3*d");
            
            return conn;
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "MySQL Connection failed");
        return null;
    } 
    }
}
